import type { Metadata } from "next";
import "@/app/ui/globals.css";

export const metadata: Metadata = {
	title: "Rocketair",
	description: "Generated by create next app",
	authors: [{ name: "Utpal", url: "https://theutpal.vercel.app" }],
	keywords: ["Next.js", "React", "TypeScript", "Rocket", "Air", "RocketAir", "Digital"],
	icons: "/favicon.png",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`antialiased bg-black`}
			>
				{children}
			</body>
		</html>
	);
}
